data_root:            ./ImageNet
wnids_file:           ./ImageNet/wnids.txt
batch_size:           32
workers:              4
epochs:               30
lr:                   0.001
momentum:             0.9
weight_decay:         0.0001
lr_step:              10
lr_gamma:             0.1
mean: [0.485, 0.456, 0.406]
std:  [0.229, 0.224, 0.225]
output_dir:           ./checkpoints/2d_baseline